/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  sym_alternation_marker = 2,
  sym_section_close = 3,
  sym_section_open = 4,
  sym_note_separator = 5,
  aux_sym_note_prefix_token1 = 6,
  sym_note_index = 7,
  aux_sym_arg_suffix_token1 = 8,
  sym_arg_value = 9,
  sym_arg_separator = 10,
  sym_root = 11,
  sym_section = 12,
  sym_alternation_section = 13,
  sym_note_sequence = 14,
  sym_full_note = 15,
  sym_raw_note = 16,
  sym_note_prefix = 17,
  sym_note_suffix = 18,
  sym_arg_sequence = 19,
  sym_arg = 20,
  sym_arg_suffix = 21,
  sym_arg_name = 22,
  aux_sym_alternation_section_repeat1 = 23,
  aux_sym_note_sequence_repeat1 = 24,
  aux_sym_arg_sequence_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [sym_alternation_marker] = "alternation_marker",
  [sym_section_close] = "section_close",
  [sym_section_open] = "section_open",
  [sym_note_separator] = "note_separator",
  [aux_sym_note_prefix_token1] = "note_prefix_token1",
  [sym_note_index] = "note_index",
  [aux_sym_arg_suffix_token1] = "arg_suffix_token1",
  [sym_arg_value] = "arg_value",
  [sym_arg_separator] = "arg_separator",
  [sym_root] = "root",
  [sym_section] = "section",
  [sym_alternation_section] = "alternation_section",
  [sym_note_sequence] = "note_sequence",
  [sym_full_note] = "full_note",
  [sym_raw_note] = "raw_note",
  [sym_note_prefix] = "note_prefix",
  [sym_note_suffix] = "note_suffix",
  [sym_arg_sequence] = "arg_sequence",
  [sym_arg] = "arg",
  [sym_arg_suffix] = "arg_suffix",
  [sym_arg_name] = "arg_name",
  [aux_sym_alternation_section_repeat1] = "alternation_section_repeat1",
  [aux_sym_note_sequence_repeat1] = "note_sequence_repeat1",
  [aux_sym_arg_sequence_repeat1] = "arg_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_alternation_marker] = sym_alternation_marker,
  [sym_section_close] = sym_section_close,
  [sym_section_open] = sym_section_open,
  [sym_note_separator] = sym_note_separator,
  [aux_sym_note_prefix_token1] = aux_sym_note_prefix_token1,
  [sym_note_index] = sym_note_index,
  [aux_sym_arg_suffix_token1] = aux_sym_arg_suffix_token1,
  [sym_arg_value] = sym_arg_value,
  [sym_arg_separator] = sym_arg_separator,
  [sym_root] = sym_root,
  [sym_section] = sym_section,
  [sym_alternation_section] = sym_alternation_section,
  [sym_note_sequence] = sym_note_sequence,
  [sym_full_note] = sym_full_note,
  [sym_raw_note] = sym_raw_note,
  [sym_note_prefix] = sym_note_prefix,
  [sym_note_suffix] = sym_note_suffix,
  [sym_arg_sequence] = sym_arg_sequence,
  [sym_arg] = sym_arg,
  [sym_arg_suffix] = sym_arg_suffix,
  [sym_arg_name] = sym_arg_name,
  [aux_sym_alternation_section_repeat1] = aux_sym_alternation_section_repeat1,
  [aux_sym_note_sequence_repeat1] = aux_sym_note_sequence_repeat1,
  [aux_sym_arg_sequence_repeat1] = aux_sym_arg_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_alternation_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_section_close] = {
    .visible = true,
    .named = true,
  },
  [sym_section_open] = {
    .visible = true,
    .named = true,
  },
  [sym_note_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_prefix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_note_index] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_arg_suffix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_arg_value] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation_section] = {
    .visible = true,
    .named = true,
  },
  [sym_note_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_full_note] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_note] = {
    .visible = true,
    .named = true,
  },
  [sym_note_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_note_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alternation_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 4,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 9,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 8,
  [30] = 7,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 21,
  [36] = 20,
  [37] = 23,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '_') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '(', 14,
        ')', 13,
        ',', 22,
        '.', 21,
        '/', 3,
        ':', 11,
        '_', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '_') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (('.' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == ',') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == ':') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == ',') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(9);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_alternation_marker);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_section_close);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_section_open);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_note_separator);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (lookahead == '_') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_note_index);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_note_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_arg_suffix_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_arg_value);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_arg_separator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 9},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_alternation_marker] = ACTIONS(1),
    [sym_section_close] = ACTIONS(1),
    [sym_section_open] = ACTIONS(1),
    [aux_sym_note_prefix_token1] = ACTIONS(1),
    [sym_note_index] = ACTIONS(1),
    [aux_sym_arg_suffix_token1] = ACTIONS(1),
    [sym_arg_value] = ACTIONS(1),
    [sym_arg_separator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_root] = STATE(44),
    [sym_section] = STATE(31),
    [sym_alternation_section] = STATE(41),
    [sym_note_sequence] = STATE(41),
    [sym_full_note] = STATE(17),
    [sym_raw_note] = STATE(22),
    [sym_note_prefix] = STATE(45),
    [sym_section_open] = ACTIONS(3),
    [aux_sym_note_prefix_token1] = ACTIONS(5),
    [sym_note_index] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_section_open,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(17), 1,
      sym_full_note,
    STATE(22), 1,
      sym_raw_note,
    STATE(40), 1,
      sym_section,
    STATE(45), 1,
      sym_note_prefix,
    STATE(42), 2,
      sym_alternation_section,
      sym_note_sequence,
  [26] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    STATE(11), 1,
      sym_note_suffix,
    ACTIONS(11), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [42] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      aux_sym_arg_suffix_token1,
    STATE(23), 1,
      sym_arg_suffix,
    ACTIONS(17), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [58] = 4,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      sym_note_suffix,
    ACTIONS(23), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [74] = 6,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(17), 1,
      sym_full_note,
    STATE(22), 1,
      sym_raw_note,
    STATE(33), 1,
      sym_note_sequence,
    STATE(45), 1,
      sym_note_prefix,
  [93] = 4,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_arg_separator,
    STATE(9), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(27), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [108] = 4,
    ACTIONS(29), 1,
      sym_arg_separator,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(33), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [123] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_arg_separator,
    STATE(9), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(37), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [138] = 3,
    ACTIONS(42), 1,
      aux_sym_arg_suffix_token1,
    STATE(37), 1,
      sym_arg_suffix,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [150] = 2,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [160] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [170] = 5,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(22), 1,
      sym_raw_note,
    STATE(27), 1,
      sym_full_note,
    STATE(45), 1,
      sym_note_prefix,
  [186] = 5,
    ACTIONS(48), 1,
      aux_sym_arg_suffix_token1,
    ACTIONS(50), 1,
      sym_arg_value,
    STATE(8), 1,
      sym_arg,
    STATE(28), 1,
      sym_arg_sequence,
    STATE(43), 1,
      sym_arg_name,
  [202] = 4,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_note_separator,
    STATE(16), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(54), 2,
      sym_alternation_marker,
      sym_section_close,
  [216] = 4,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym_note_separator,
    STATE(16), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(60), 2,
      sym_alternation_marker,
      sym_section_close,
  [230] = 4,
    ACTIONS(56), 1,
      sym_note_separator,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(67), 2,
      sym_alternation_marker,
      sym_section_close,
  [244] = 2,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [254] = 5,
    ACTIONS(48), 1,
      aux_sym_arg_suffix_token1,
    ACTIONS(73), 1,
      sym_arg_value,
    STATE(29), 1,
      sym_arg,
    STATE(39), 1,
      sym_arg_sequence,
    STATE(48), 1,
      sym_arg_name,
  [270] = 2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [280] = 2,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [290] = 3,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      anon_sym_COLON,
    ACTIONS(83), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [302] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [312] = 3,
    ACTIONS(89), 1,
      sym_arg_separator,
    STATE(24), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [323] = 3,
    ACTIONS(94), 1,
      sym_alternation_marker,
    STATE(26), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [334] = 3,
    ACTIONS(98), 1,
      sym_alternation_marker,
    STATE(26), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [345] = 2,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [354] = 2,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [363] = 3,
    ACTIONS(105), 1,
      sym_arg_separator,
    STATE(30), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [374] = 3,
    ACTIONS(105), 1,
      sym_arg_separator,
    STATE(24), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [385] = 3,
    ACTIONS(94), 1,
      sym_alternation_marker,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_alternation_section_repeat1,
  [395] = 3,
    ACTIONS(48), 1,
      aux_sym_arg_suffix_token1,
    STATE(21), 1,
      sym_arg,
    STATE(43), 1,
      sym_arg_name,
  [405] = 1,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_section_close,
  [411] = 2,
    ACTIONS(111), 1,
      anon_sym_COLON,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [419] = 1,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [425] = 1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [431] = 1,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [437] = 3,
    ACTIONS(48), 1,
      aux_sym_arg_suffix_token1,
    STATE(35), 1,
      sym_arg,
    STATE(48), 1,
      sym_arg_name,
  [447] = 1,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [452] = 2,
    ACTIONS(94), 1,
      sym_alternation_marker,
    STATE(25), 1,
      aux_sym_alternation_section_repeat1,
  [459] = 1,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [464] = 2,
    ACTIONS(115), 1,
      sym_alternation_marker,
    ACTIONS(117), 1,
      sym_section_close,
  [471] = 1,
    ACTIONS(119), 1,
      sym_arg_value,
  [475] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
  [479] = 1,
    ACTIONS(123), 1,
      sym_note_index,
  [483] = 1,
    ACTIONS(125), 1,
      sym_note_index,
  [487] = 1,
    ACTIONS(127), 1,
      sym_arg_value,
  [491] = 1,
    ACTIONS(129), 1,
      sym_arg_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 93,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 123,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 150,
  [SMALL_STATE(12)] = 160,
  [SMALL_STATE(13)] = 170,
  [SMALL_STATE(14)] = 186,
  [SMALL_STATE(15)] = 202,
  [SMALL_STATE(16)] = 216,
  [SMALL_STATE(17)] = 230,
  [SMALL_STATE(18)] = 244,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 270,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 290,
  [SMALL_STATE(23)] = 302,
  [SMALL_STATE(24)] = 312,
  [SMALL_STATE(25)] = 323,
  [SMALL_STATE(26)] = 334,
  [SMALL_STATE(27)] = 345,
  [SMALL_STATE(28)] = 354,
  [SMALL_STATE(29)] = 363,
  [SMALL_STATE(30)] = 374,
  [SMALL_STATE(31)] = 385,
  [SMALL_STATE(32)] = 395,
  [SMALL_STATE(33)] = 405,
  [SMALL_STATE(34)] = 411,
  [SMALL_STATE(35)] = 419,
  [SMALL_STATE(36)] = 425,
  [SMALL_STATE(37)] = 431,
  [SMALL_STATE(38)] = 437,
  [SMALL_STATE(39)] = 447,
  [SMALL_STATE(40)] = 452,
  [SMALL_STATE(41)] = 459,
  [SMALL_STATE(42)] = 464,
  [SMALL_STATE(43)] = 471,
  [SMALL_STATE(44)] = 475,
  [SMALL_STATE(45)] = 479,
  [SMALL_STATE(46)] = 483,
  [SMALL_STATE(47)] = 487,
  [SMALL_STATE(48)] = 491,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_suffix, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_suffix, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 3, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation_section, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_prefix, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_name, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shuttle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "shuttle",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 3,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
