/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  sym_alternation_marker = 2,
  sym_section_close = 3,
  sym_section_open = 4,
  sym_note_separator = 5,
  aux_sym_note_prefix_token1 = 6,
  sym_note_index = 7,
  sym_arg_name = 8,
  sym_arg_value = 9,
  sym_arg_separator = 10,
  sym_root = 11,
  sym_section = 12,
  sym_alternation_section = 13,
  sym_note_sequence = 14,
  sym_full_note = 15,
  sym_raw_note = 16,
  sym_note_prefix = 17,
  sym_note_suffix = 18,
  sym_arg_sequence = 19,
  sym_arg = 20,
  aux_sym_alternation_section_repeat1 = 21,
  aux_sym_note_sequence_repeat1 = 22,
  aux_sym_arg_sequence_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [sym_alternation_marker] = "alternation_marker",
  [sym_section_close] = "section_close",
  [sym_section_open] = "section_open",
  [sym_note_separator] = "note_separator",
  [aux_sym_note_prefix_token1] = "note_prefix_token1",
  [sym_note_index] = "note_index",
  [sym_arg_name] = "arg_name",
  [sym_arg_value] = "arg_value",
  [sym_arg_separator] = "arg_separator",
  [sym_root] = "root",
  [sym_section] = "section",
  [sym_alternation_section] = "alternation_section",
  [sym_note_sequence] = "note_sequence",
  [sym_full_note] = "full_note",
  [sym_raw_note] = "raw_note",
  [sym_note_prefix] = "note_prefix",
  [sym_note_suffix] = "note_suffix",
  [sym_arg_sequence] = "arg_sequence",
  [sym_arg] = "arg",
  [aux_sym_alternation_section_repeat1] = "alternation_section_repeat1",
  [aux_sym_note_sequence_repeat1] = "note_sequence_repeat1",
  [aux_sym_arg_sequence_repeat1] = "arg_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_alternation_marker] = sym_alternation_marker,
  [sym_section_close] = sym_section_close,
  [sym_section_open] = sym_section_open,
  [sym_note_separator] = sym_note_separator,
  [aux_sym_note_prefix_token1] = aux_sym_note_prefix_token1,
  [sym_note_index] = sym_note_index,
  [sym_arg_name] = sym_arg_name,
  [sym_arg_value] = sym_arg_value,
  [sym_arg_separator] = sym_arg_separator,
  [sym_root] = sym_root,
  [sym_section] = sym_section,
  [sym_alternation_section] = sym_alternation_section,
  [sym_note_sequence] = sym_note_sequence,
  [sym_full_note] = sym_full_note,
  [sym_raw_note] = sym_raw_note,
  [sym_note_prefix] = sym_note_prefix,
  [sym_note_suffix] = sym_note_suffix,
  [sym_arg_sequence] = sym_arg_sequence,
  [sym_arg] = sym_arg,
  [aux_sym_alternation_section_repeat1] = aux_sym_alternation_section_repeat1,
  [aux_sym_note_sequence_repeat1] = aux_sym_note_sequence_repeat1,
  [aux_sym_arg_sequence_repeat1] = aux_sym_arg_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_alternation_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_section_close] = {
    .visible = true,
    .named = true,
  },
  [sym_section_open] = {
    .visible = true,
    .named = true,
  },
  [sym_note_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_prefix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_note_index] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_value] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation_section] = {
    .visible = true,
    .named = true,
  },
  [sym_note_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_full_note] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_note] = {
    .visible = true,
    .named = true,
  },
  [sym_note_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_note_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alternation_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 7,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 5,
  [26] = 26,
  [27] = 8,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 18,
  [32] = 17,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 34,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '_') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '(', 11,
        ')', 10,
        ',', 19,
        '.', 18,
        '/', 3,
        ':', 8,
        '_', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '_') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ':') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_alternation_marker);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_section_close);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_section_open);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_note_separator);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (lookahead == '_') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_note_index);
      if (lookahead == '.') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_note_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_arg_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_arg_value);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_arg_separator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_alternation_marker] = ACTIONS(1),
    [sym_section_close] = ACTIONS(1),
    [sym_section_open] = ACTIONS(1),
    [aux_sym_note_prefix_token1] = ACTIONS(1),
    [sym_note_index] = ACTIONS(1),
    [sym_arg_name] = ACTIONS(1),
    [sym_arg_value] = ACTIONS(1),
    [sym_arg_separator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_root] = STATE(40),
    [sym_section] = STATE(30),
    [sym_alternation_section] = STATE(33),
    [sym_note_sequence] = STATE(33),
    [sym_full_note] = STATE(10),
    [sym_raw_note] = STATE(14),
    [sym_note_prefix] = STATE(41),
    [sym_section_open] = ACTIONS(3),
    [aux_sym_note_prefix_token1] = ACTIONS(5),
    [sym_note_index] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_section_open,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(10), 1,
      sym_full_note,
    STATE(14), 1,
      sym_raw_note,
    STATE(35), 1,
      sym_section,
    STATE(41), 1,
      sym_note_prefix,
    STATE(37), 2,
      sym_alternation_section,
      sym_note_sequence,
  [26] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    STATE(15), 1,
      sym_note_suffix,
    ACTIONS(11), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [42] = 4,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_note_suffix,
    ACTIONS(17), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [58] = 4,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_arg_separator,
    STATE(7), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(21), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [73] = 6,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(10), 1,
      sym_full_note,
    STATE(14), 1,
      sym_raw_note,
    STATE(29), 1,
      sym_note_sequence,
    STATE(41), 1,
      sym_note_prefix,
  [92] = 4,
    ACTIONS(23), 1,
      sym_arg_separator,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(27), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [107] = 4,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      sym_arg_separator,
    STATE(8), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(31), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [122] = 2,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [132] = 4,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_note_separator,
    STATE(12), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(38), 2,
      sym_alternation_marker,
      sym_section_close,
  [146] = 5,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(14), 1,
      sym_raw_note,
    STATE(22), 1,
      sym_full_note,
    STATE(41), 1,
      sym_note_prefix,
  [162] = 4,
    ACTIONS(40), 1,
      sym_note_separator,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(44), 2,
      sym_alternation_marker,
      sym_section_close,
  [176] = 2,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [186] = 3,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      anon_sym_COLON,
    ACTIONS(54), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [198] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [208] = 4,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_note_separator,
    STATE(16), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(62), 2,
      sym_alternation_marker,
      sym_section_close,
  [222] = 2,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [232] = 2,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [242] = 3,
    ACTIONS(71), 1,
      sym_arg_separator,
    STATE(27), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [253] = 3,
    ACTIONS(75), 1,
      sym_alternation_marker,
    STATE(20), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [264] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [273] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [282] = 4,
    ACTIONS(82), 1,
      sym_arg_name,
    ACTIONS(84), 1,
      sym_arg_value,
    STATE(25), 1,
      sym_arg,
    STATE(36), 1,
      sym_arg_sequence,
  [295] = 3,
    ACTIONS(88), 1,
      sym_alternation_marker,
    STATE(20), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [306] = 3,
    ACTIONS(71), 1,
      sym_arg_separator,
    STATE(19), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [317] = 4,
    ACTIONS(90), 1,
      sym_arg_name,
    ACTIONS(92), 1,
      sym_arg_value,
    STATE(5), 1,
      sym_arg,
    STATE(21), 1,
      sym_arg_sequence,
  [330] = 3,
    ACTIONS(94), 1,
      sym_arg_separator,
    STATE(27), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [341] = 2,
    ACTIONS(99), 1,
      anon_sym_COLON,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [349] = 1,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_section_close,
  [355] = 3,
    ACTIONS(88), 1,
      sym_alternation_marker,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_alternation_section_repeat1,
  [365] = 1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [371] = 1,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_arg_separator,
  [377] = 1,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [382] = 2,
    ACTIONS(90), 1,
      sym_arg_name,
    STATE(18), 1,
      sym_arg,
  [389] = 2,
    ACTIONS(88), 1,
      sym_alternation_marker,
    STATE(24), 1,
      aux_sym_alternation_section_repeat1,
  [396] = 1,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_alternation_marker,
  [401] = 2,
    ACTIONS(103), 1,
      sym_alternation_marker,
    ACTIONS(107), 1,
      sym_section_close,
  [408] = 2,
    ACTIONS(82), 1,
      sym_arg_name,
    STATE(31), 1,
      sym_arg,
  [415] = 1,
    ACTIONS(109), 1,
      sym_arg_value,
  [419] = 1,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
  [423] = 1,
    ACTIONS(113), 1,
      sym_note_index,
  [427] = 1,
    ACTIONS(115), 1,
      sym_note_index,
  [431] = 1,
    ACTIONS(117), 1,
      sym_arg_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 73,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 122,
  [SMALL_STATE(10)] = 132,
  [SMALL_STATE(11)] = 146,
  [SMALL_STATE(12)] = 162,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 186,
  [SMALL_STATE(15)] = 198,
  [SMALL_STATE(16)] = 208,
  [SMALL_STATE(17)] = 222,
  [SMALL_STATE(18)] = 232,
  [SMALL_STATE(19)] = 242,
  [SMALL_STATE(20)] = 253,
  [SMALL_STATE(21)] = 264,
  [SMALL_STATE(22)] = 273,
  [SMALL_STATE(23)] = 282,
  [SMALL_STATE(24)] = 295,
  [SMALL_STATE(25)] = 306,
  [SMALL_STATE(26)] = 317,
  [SMALL_STATE(27)] = 330,
  [SMALL_STATE(28)] = 341,
  [SMALL_STATE(29)] = 349,
  [SMALL_STATE(30)] = 355,
  [SMALL_STATE(31)] = 365,
  [SMALL_STATE(32)] = 371,
  [SMALL_STATE(33)] = 377,
  [SMALL_STATE(34)] = 382,
  [SMALL_STATE(35)] = 389,
  [SMALL_STATE(36)] = 396,
  [SMALL_STATE(37)] = 401,
  [SMALL_STATE(38)] = 408,
  [SMALL_STATE(39)] = 415,
  [SMALL_STATE(40)] = 419,
  [SMALL_STATE(41)] = 423,
  [SMALL_STATE(42)] = 427,
  [SMALL_STATE(43)] = 431,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation_section, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [111] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_prefix, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_LOWER_PARSER_NAME(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "LOWER_PARSER_NAME",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
