/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  sym_alternation_marker = 2,
  sym_section_close = 3,
  sym_section_open = 4,
  sym_note_separator = 5,
  aux_sym_note_prefix_token1 = 6,
  sym_note_index = 7,
  aux_sym_arg_suffix_token1 = 8,
  sym_arg_value = 9,
  sym_arg_separator = 10,
  sym_root = 11,
  sym_expression = 12,
  sym_bracket_section = 13,
  sym_alternation_section = 14,
  sym_segment = 15,
  sym_note_sequence = 16,
  sym_full_note = 17,
  sym_raw_note = 18,
  sym_note_prefix = 19,
  sym_note_suffix = 20,
  sym_arg_sequence = 21,
  sym_arg = 22,
  sym_arg_suffix = 23,
  sym_arg_name = 24,
  aux_sym_alternation_section_repeat1 = 25,
  aux_sym_segment_repeat1 = 26,
  aux_sym_note_sequence_repeat1 = 27,
  aux_sym_arg_sequence_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [sym_alternation_marker] = "alternation_marker",
  [sym_section_close] = "section_close",
  [sym_section_open] = "section_open",
  [sym_note_separator] = "note_separator",
  [aux_sym_note_prefix_token1] = "note_prefix_token1",
  [sym_note_index] = "note_index",
  [aux_sym_arg_suffix_token1] = "arg_suffix_token1",
  [sym_arg_value] = "arg_value",
  [sym_arg_separator] = "arg_separator",
  [sym_root] = "root",
  [sym_expression] = "expression",
  [sym_bracket_section] = "bracket_section",
  [sym_alternation_section] = "alternation_section",
  [sym_segment] = "segment",
  [sym_note_sequence] = "note_sequence",
  [sym_full_note] = "full_note",
  [sym_raw_note] = "raw_note",
  [sym_note_prefix] = "note_prefix",
  [sym_note_suffix] = "note_suffix",
  [sym_arg_sequence] = "arg_sequence",
  [sym_arg] = "arg",
  [sym_arg_suffix] = "arg_suffix",
  [sym_arg_name] = "arg_name",
  [aux_sym_alternation_section_repeat1] = "alternation_section_repeat1",
  [aux_sym_segment_repeat1] = "segment_repeat1",
  [aux_sym_note_sequence_repeat1] = "note_sequence_repeat1",
  [aux_sym_arg_sequence_repeat1] = "arg_sequence_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_alternation_marker] = sym_alternation_marker,
  [sym_section_close] = sym_section_close,
  [sym_section_open] = sym_section_open,
  [sym_note_separator] = sym_note_separator,
  [aux_sym_note_prefix_token1] = aux_sym_note_prefix_token1,
  [sym_note_index] = sym_note_index,
  [aux_sym_arg_suffix_token1] = aux_sym_arg_suffix_token1,
  [sym_arg_value] = sym_arg_value,
  [sym_arg_separator] = sym_arg_separator,
  [sym_root] = sym_root,
  [sym_expression] = sym_expression,
  [sym_bracket_section] = sym_bracket_section,
  [sym_alternation_section] = sym_alternation_section,
  [sym_segment] = sym_segment,
  [sym_note_sequence] = sym_note_sequence,
  [sym_full_note] = sym_full_note,
  [sym_raw_note] = sym_raw_note,
  [sym_note_prefix] = sym_note_prefix,
  [sym_note_suffix] = sym_note_suffix,
  [sym_arg_sequence] = sym_arg_sequence,
  [sym_arg] = sym_arg,
  [sym_arg_suffix] = sym_arg_suffix,
  [sym_arg_name] = sym_arg_name,
  [aux_sym_alternation_section_repeat1] = aux_sym_alternation_section_repeat1,
  [aux_sym_segment_repeat1] = aux_sym_segment_repeat1,
  [aux_sym_note_sequence_repeat1] = aux_sym_note_sequence_repeat1,
  [aux_sym_arg_sequence_repeat1] = aux_sym_arg_sequence_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_alternation_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_section_close] = {
    .visible = true,
    .named = true,
  },
  [sym_section_open] = {
    .visible = true,
    .named = true,
  },
  [sym_note_separator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_prefix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_note_index] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_arg_suffix_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_arg_value] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_section] = {
    .visible = true,
    .named = true,
  },
  [sym_alternation_section] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_note_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_full_note] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_note] = {
    .visible = true,
    .named = true,
  },
  [sym_note_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_note_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alternation_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_segment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '_') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 1,
        '(', 12,
        ')', 11,
        ',', 20,
        '.', 19,
        '/', 3,
        ':', 9,
        '_', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '_') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == ':') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_alternation_marker);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_section_close);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_section_open);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_note_separator);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (lookahead == '_') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_note_prefix_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_note_index);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_note_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_arg_suffix_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_arg_value);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_arg_separator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_alternation_marker] = ACTIONS(1),
    [sym_section_close] = ACTIONS(1),
    [sym_section_open] = ACTIONS(1),
    [aux_sym_note_prefix_token1] = ACTIONS(1),
    [sym_note_index] = ACTIONS(1),
    [aux_sym_arg_suffix_token1] = ACTIONS(1),
    [sym_arg_value] = ACTIONS(1),
    [sym_arg_separator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_root] = STATE(45),
    [sym_expression] = STATE(41),
    [sym_bracket_section] = STATE(11),
    [sym_alternation_section] = STATE(44),
    [sym_segment] = STATE(36),
    [sym_note_sequence] = STATE(11),
    [sym_full_note] = STATE(12),
    [sym_raw_note] = STATE(16),
    [sym_note_prefix] = STATE(38),
    [sym_section_open] = ACTIONS(3),
    [aux_sym_note_prefix_token1] = ACTIONS(5),
    [sym_note_index] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_section_open,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(12), 1,
      sym_full_note,
    STATE(16), 1,
      sym_raw_note,
    STATE(35), 1,
      sym_segment,
    STATE(38), 1,
      sym_note_prefix,
    STATE(40), 1,
      sym_alternation_section,
    STATE(11), 2,
      sym_bracket_section,
      sym_note_sequence,
  [29] = 8,
    ACTIONS(3), 1,
      sym_section_open,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(12), 1,
      sym_full_note,
    STATE(16), 1,
      sym_raw_note,
    STATE(37), 1,
      sym_segment,
    STATE(38), 1,
      sym_note_prefix,
    STATE(11), 2,
      sym_bracket_section,
      sym_note_sequence,
  [55] = 7,
    ACTIONS(3), 1,
      sym_section_open,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(12), 1,
      sym_full_note,
    STATE(16), 1,
      sym_raw_note,
    STATE(38), 1,
      sym_note_prefix,
    STATE(33), 2,
      sym_bracket_section,
      sym_note_sequence,
  [78] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    STATE(13), 1,
      sym_note_suffix,
    ACTIONS(11), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [94] = 4,
    ACTIONS(13), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_note_suffix,
    ACTIONS(17), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [110] = 4,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      aux_sym_arg_suffix_token1,
    STATE(27), 1,
      sym_arg_suffix,
    ACTIONS(21), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [126] = 4,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_arg_separator,
    STATE(8), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(27), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [141] = 4,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym_arg_separator,
    STATE(8), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(34), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [156] = 4,
    ACTIONS(36), 1,
      sym_arg_separator,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_arg_sequence_repeat1,
    ACTIONS(40), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [171] = 4,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      sym_note_separator,
    STATE(14), 1,
      aux_sym_segment_repeat1,
    ACTIONS(44), 2,
      sym_alternation_marker,
      sym_section_close,
  [185] = 4,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_note_separator,
    STATE(18), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(50), 2,
      sym_alternation_marker,
      sym_section_close,
  [199] = 2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [209] = 4,
    ACTIONS(46), 1,
      sym_note_separator,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_segment_repeat1,
    ACTIONS(56), 2,
      sym_alternation_marker,
      sym_section_close,
  [223] = 2,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [233] = 3,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      anon_sym_COLON,
    ACTIONS(66), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [245] = 5,
    ACTIONS(5), 1,
      aux_sym_note_prefix_token1,
    ACTIONS(7), 1,
      sym_note_index,
    STATE(16), 1,
      sym_raw_note,
    STATE(30), 1,
      sym_full_note,
    STATE(38), 1,
      sym_note_prefix,
  [261] = 3,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(70), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [273] = 5,
    ACTIONS(72), 1,
      aux_sym_arg_suffix_token1,
    ACTIONS(74), 1,
      sym_arg_value,
    STATE(10), 1,
      sym_arg,
    STATE(31), 1,
      sym_arg_sequence,
    STATE(43), 1,
      sym_arg_name,
  [289] = 4,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      sym_note_separator,
    STATE(20), 1,
      aux_sym_segment_repeat1,
    ACTIONS(78), 2,
      sym_alternation_marker,
      sym_section_close,
  [303] = 5,
    ACTIONS(72), 1,
      aux_sym_arg_suffix_token1,
    ACTIONS(74), 1,
      sym_arg_value,
    STATE(10), 1,
      sym_arg,
    STATE(32), 1,
      sym_arg_sequence,
    STATE(43), 1,
      sym_arg_name,
  [319] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 4,
      anon_sym_COLON,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [329] = 3,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      anon_sym_COLON,
    ACTIONS(91), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [341] = 2,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [351] = 4,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym_note_separator,
    STATE(25), 1,
      aux_sym_note_sequence_repeat1,
    ACTIONS(95), 2,
      sym_alternation_marker,
      sym_section_close,
  [365] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [375] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 4,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
      sym_arg_separator,
  [385] = 3,
    ACTIONS(110), 1,
      sym_alternation_marker,
    STATE(29), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [396] = 3,
    ACTIONS(114), 1,
      sym_alternation_marker,
    STATE(29), 1,
      aux_sym_alternation_section_repeat1,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_section_close,
  [407] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [416] = 2,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [425] = 2,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [434] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 3,
      sym_alternation_marker,
      sym_section_close,
      sym_note_separator,
  [443] = 3,
    ACTIONS(72), 1,
      aux_sym_arg_suffix_token1,
    STATE(24), 1,
      sym_arg,
    STATE(43), 1,
      sym_arg_name,
  [453] = 3,
    ACTIONS(110), 1,
      sym_alternation_marker,
    ACTIONS(125), 1,
      sym_section_close,
    STATE(28), 1,
      aux_sym_alternation_section_repeat1,
  [463] = 3,
    ACTIONS(110), 1,
      sym_alternation_marker,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      aux_sym_alternation_section_repeat1,
  [473] = 1,
    ACTIONS(112), 3,
      ts_builtin_sym_end,
      sym_alternation_marker,
      sym_section_close,
  [479] = 1,
    ACTIONS(129), 1,
      sym_note_index,
  [483] = 1,
    ACTIONS(131), 1,
      sym_arg_value,
  [487] = 1,
    ACTIONS(125), 1,
      sym_section_close,
  [491] = 1,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
  [495] = 1,
    ACTIONS(135), 1,
      sym_note_index,
  [499] = 1,
    ACTIONS(137), 1,
      sym_arg_value,
  [503] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [507] = 1,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 55,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 110,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 141,
  [SMALL_STATE(10)] = 156,
  [SMALL_STATE(11)] = 171,
  [SMALL_STATE(12)] = 185,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 209,
  [SMALL_STATE(15)] = 223,
  [SMALL_STATE(16)] = 233,
  [SMALL_STATE(17)] = 245,
  [SMALL_STATE(18)] = 261,
  [SMALL_STATE(19)] = 273,
  [SMALL_STATE(20)] = 289,
  [SMALL_STATE(21)] = 303,
  [SMALL_STATE(22)] = 319,
  [SMALL_STATE(23)] = 329,
  [SMALL_STATE(24)] = 341,
  [SMALL_STATE(25)] = 351,
  [SMALL_STATE(26)] = 365,
  [SMALL_STATE(27)] = 375,
  [SMALL_STATE(28)] = 385,
  [SMALL_STATE(29)] = 396,
  [SMALL_STATE(30)] = 407,
  [SMALL_STATE(31)] = 416,
  [SMALL_STATE(32)] = 425,
  [SMALL_STATE(33)] = 434,
  [SMALL_STATE(34)] = 443,
  [SMALL_STATE(35)] = 453,
  [SMALL_STATE(36)] = 463,
  [SMALL_STATE(37)] = 473,
  [SMALL_STATE(38)] = 479,
  [SMALL_STATE(39)] = 483,
  [SMALL_STATE(40)] = 487,
  [SMALL_STATE(41)] = 491,
  [SMALL_STATE(42)] = 495,
  [SMALL_STATE(43)] = 499,
  [SMALL_STATE(44)] = 503,
  [SMALL_STATE(45)] = 507,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_sequence, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_segment, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_suffix, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_sequence, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_note, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_note, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_section, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_section, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_note_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_suffix, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_suffix, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternation_section, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_alternation_section_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_note, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_note, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_section, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_section, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_name, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_prefix, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [139] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_shuttle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "shuttle",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 4,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
